// <auto-generated />
using System;
using Ghita_Vlad_Proiect_Facturi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ghita_Vlad_Proiect_Facturi.Migrations
{
    [DbContext(typeof(GhitaVladProiectFacturiContext))]
    [Migration("20260120151835_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ghita_Vlad_Proiect_Facturi.Models.Factura", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DataEmiterii")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataScadentei")
                        .HasColumnType("datetime2");

                    b.Property<int>("Numar")
                        .HasColumnType("int");

                    b.Property<int>("PartenerID")
                        .HasColumnType("int");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Stare")
                        .HasColumnType("int");

                    b.Property<int>("TipFactura")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("PartenerID");

                    b.ToTable("Facturi");
                });

            modelBuilder.Entity("Ghita_Vlad_Proiect_Facturi.Models.Partener", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adresa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CUI")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Parteneri");
                });

            modelBuilder.Entity("Ghita_Vlad_Proiect_Facturi.Models.Plata", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DataPlatii")
                        .HasColumnType("datetime2");

                    b.Property<int>("FacturaID")
                        .HasColumnType("int");

                    b.Property<int>("MetodaPlata")
                        .HasColumnType("int");

                    b.Property<string>("Observatii")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Suma")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("FacturaID");

                    b.ToTable("Plati");
                });

            modelBuilder.Entity("Ghita_Vlad_Proiect_Facturi.Models.Produs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descriere")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NumeProdus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PretUnitar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Produse");
                });

            modelBuilder.Entity("Ghita_Vlad_Proiect_Facturi.Models.Factura", b =>
                {
                    b.HasOne("Ghita_Vlad_Proiect_Facturi.Models.Partener", "Partener")
                        .WithMany("Facturi")
                        .HasForeignKey("PartenerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partener");
                });

            modelBuilder.Entity("Ghita_Vlad_Proiect_Facturi.Models.Plata", b =>
                {
                    b.HasOne("Ghita_Vlad_Proiect_Facturi.Models.Factura", "Factura")
                        .WithMany("Plati")
                        .HasForeignKey("FacturaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("Ghita_Vlad_Proiect_Facturi.Models.Factura", b =>
                {
                    b.Navigation("Plati");
                });

            modelBuilder.Entity("Ghita_Vlad_Proiect_Facturi.Models.Partener", b =>
                {
                    b.Navigation("Facturi");
                });
#pragma warning restore 612, 618
        }
    }
}
